### ISSUE TITLE
naming: IV v.s. OV

### ISSUE THREAD

**Issue by FranklinYu** [yunzhu-li/certificate-info#23]
Is there any source referring to them as IV? All the articles I found are talking about DV, OV, and EV.

**Comment by yunzhu-li** [comment]
No, this does not follow that naming convention since the extension cannot distinguish certificates issued to organizations vs individuals even though "OV" often covers individual certificates as well ([1]).

[1]: https://wiki.mozilla.org/CA/Terminology

**Comment by FranklinYu** [comment]
Thanks for the link. Technically it doesn’t directly mention “identity validation” as a term, but I think it’s fair enough.
